### PR TITLE
Feature/add eva json

### PR DESCRIPTION
**Pull request by gnaamati**
Add JSON files to fetch variation data from EVA

### CODE REVIEW

**Comment by ens-st3** [comment]
Our recent experience with EBI FTP site is that it can be a bit unstable. Another option (which you made some changes for already I think ?) is to copy files to internal FS and read them from there

**Comment by gnaamati** [comment]
Hi Steve, I was following the instructions by variation written here:
https://www.ebi.ac.uk/seqdb/confluence/display/EV/Instructions+for+adding+variants+for+Atlantic+salmon+from+EVA
In their example they link directly to the EVA site.

I think the idea behind getting variation data from EVA is to link directly to them and not have local copies (also some of the files are quite big). If you think otherwise (or there are things I misunderstood) I can ask variation again.

**Comment by gnaamati** [comment]
In any case I have asked variation about what they usually do

**Comment by gnaamati** [comment]
I have asked variation and they are all directly getting the data from the EVA FTP server.
According to them there haven't been any problems with stability for a long time.

**Comment by ens-st3** [comment]
That's good - there are different deployments of FTP sites and if EVA is more stable than ftp.ensembl.org that's great.

**Comment by gnaamati** [comment]
Thanks Steve. In any case we will keep our eye on this.

**Comment by imransl** [comment]
@gnaamati Is this PR for 101 or 102?

**Comment by gnaamati** [comment]
This is for 102, thanks

**Comment by imransl** [comment]
Thanks @gnaamati. I'll change base branch to master and merge this.

**Pull request merged**
