### PR TITLE
Update zea_mays.ini

### PR DESCRIPTION
**Pull request by weix-cshl**
Comment out the BAM tracks mapped to Maize AGPv4

### CODE REVIEW

**Review by ens-ap5 — APPROVED** [review]
Will need doing on release/eg/52 now as well, since we already branched.

**Review by gnaamati — APPROVED** [review]

**Comment by ens-ds23** [comment]
About to merge this now @gnaamati  @weix-cshl . Is there an easy way to check on test that these changes have taken effect on plants test? Or if it's a zero-effect change, that whatever-it-is still works? I'll apply it either way, but just for peace of mind!

**Comment by ens-ds23** [comment]
Just saw you were involved as well, @imransl . Do you know of a good way to test this?

**Comment by imransl** [comment]
> Just saw you were involved as well, @imransl . Do you know of a good way to test this?

@ens-ds23 Might be able to test this with my sandbox. I'll try to get my sandbox on the same branch as this PR and post the link to it here.

**Comment by ens-ds23** [comment]
Thanks @imransl . I'll merge now anyway. If you could test tomorrow that would be great. If anything's wrong, we can do it as a post release fix tomorrow or Friday.

**Comment by imransl** [comment]
@ens-ds23 @ens-ap5 I've got my sandbox to work with this PR's branch: http://wp-np2-1e.ebi.ac.uk:9310/Zea_mays/Location/View?db=core;g=Zm00001eb404730;r=9:162874053-162897629

**Comment by ens-ds23** [comment]
Thanks @imransl !

**Comment by gnaamati** [comment]
Hi all, I'm having a meeting with @weix-cshl tomorrow and we can look at this together - will update
Guy

**Pull request merged**
