### PR TITLE
added apple attached VCF config

### PR DESCRIPTION
**Pull request by brunocontrerasmoreira**
Hi, this is a new JSON file for apple (malus_domestica) variants in attached VCF form.

It has been tested on a sandbox.

### CODE REVIEW

**Comment by brunocontrerasmoreira** [comment]
Yes, as soon as production give us a folder and access to it

**Comment by brunocontrerasmoreira** [comment]
Done @ens-st3 I hope it is correct now

**Comment by eead-csic-compbio** [comment]
Good morning @ens-st3  , please let me know when you apply this as I need to test apple in staging and cant see the genotypes yet:
http://staging-plants.ensembl.org/Malus_domestica/Variation/Explore?db=core;r=13:3058587-3060356;v=Chr13_3058814;vdb=variation;vf=7507670

**Comment by ens-st3** [comment]
Hi - this will also require the copying of the files to our internal filesystem.

**Comment by eead-csic-compbio** [comment]
OK, and I guess you still don't have a final destination in your filesystem, right? Currently, this file lives at ```/nfs/panda/ensemblgenomes/ftp/pub/misc_data/vcf/malus_domestica```

**Comment by brunocontrerasmoreira** [comment]
Hi @steve, following @james-monkeyshines messages on ticket https://www.ebi.ac.uk/panda/jira/browse/ENSINT-407 , I have tried to make the right fixes in the json files for apple, wheat and rice, which already live at /nfs/production/panda/ensembl/production/ensemblftp/data_files_nv

Let me know if these are fine with you

**Comment by brunocontrerasmoreira** [comment]
Thanks @steve, please let us know when the new code is in staging so that we can check the data

**Pull request merged**
