### PR TITLE
INI hacking, with the aim of improving phytozome browser links 

### PR DESCRIPTION
**Pull request by dbolser-ebi**
I spent a bit of time cleaning up and debugging the INIs, and finally set to work updating and adding links to phytozome.

### CODE REVIEW

**Comment by dbolser-ebi** [comment]
GitHub suggested a reviewer! (i.e. don't blame me ;-)

**Comment by nicklangridge** [comment]
I've merged it anyway as having the DAS config won't hurt - I'd suggest removing it when you have a chance.

**Comment by dbolser-ebi** [comment]
I'm continuing to work on Phytozome links today, so I'll remove it. One ini
actually has a value for this header:

[ENSEMBL_INTERNAL_DAS_SOURCES]
MAKERP = gene_transcript


I'm assuming that is now defunct?
​

**Comment by ens-ap5** [comment]
100%. I stripped out all the DAS code a couple of years ago. There are a few orphan files lurking here and there, but they have no effect on the site.

Anne

**Pull request merged**
