### PR TITLE
Updated TAXON_ORDER

### PR DESCRIPTION
**Pull request by brunocontrerasmoreira**
Hi @ens-ap5 @gnaamati ,
hopefully this will fix the issue of Amborellales being below eukaryotes

### CODE REVIEW

**Comment by brunocontrerasmoreira** [comment]
I'll add @imransl too

**Review by ens-ap5 — APPROVED** [review]
Yep, that will do it!

**Comment by brunocontrerasmoreira** [comment]
Thanks

**Comment by brunocontrerasmoreira** [comment]
Thanks, please let me know when this is live so I can check out how it looks.

**Comment by imransl** [comment]
@brunocontrerasmoreira The plants staging has been updated with the changes

**Comment by brunocontrerasmoreira** [comment]
Can't see any difference @ens-ap5 , Chara is still shown as Eukaryota, while I was expeting it to appear within Amborellales, any ideas?

**Comment by imransl** [comment]
@brunocontrerasmoreira I didn't do the update properly the last time. Can you check the staging and the live sites again?

**Comment by brunocontrerasmoreira** [comment]
That explains it, now it looks good, thanks for your help!

**Comment by imransl** [comment]
No problem!

**Pull request merged**
