### PR TITLE
More config tinkering to pull

### PR DESCRIPTION
**Pull request by dbolser-ebi**
Sorry for late testing!

Please can you repack after pulling?

### CODE REVIEW

**Comment by dbolser-ebi** [comment]
I just realised I can pull this myself... In general should I do that?

**Comment by nicklangridge** [comment]
sorry missed this - still required? to which branches should it be applied?

**Comment by dbolser-ebi** [comment]
Yes please, on master and release/91 or release/38 but not release/90 or release/37

**Comment by nicklangridge** [comment]
Applied to master and release/eg/38

**Pull request merged**
