### PR TITLE
Remove the New Relic script from the Plants site

### PR DESCRIPTION
**Pull request by azangru**
I am seeing a network error on the Plants site due to a call to the New Relic monitoring service, which we aren't using any longer:

Screenshot 2021-09-01 at 01 08 58

This PR removes the file that makes this call

### CODE REVIEW

**Comment by ens-ap5** [comment]
Do we know where this script is loaded and called from? I've never heard of it before, and I thought only the numbered JS files were compiled into our minified JS.

**Comment by jyothishnt** [comment]
> Do we know where this script is loaded and called from? I've never heard of it before, and I thought only the numbered JS files were compiled into our minified JS.

Hi @ens-ap5  IIRC all files inside htdocs/components are considered for minification. The numbers are for the loading order.
https://github.com/Ensembl/ensembl-webcode/blob/release/104/modules/EnsEMBL/Web/Tools/DHTMLmerge.pm#L223

**Comment by ens-ma7** [comment]
I look into this a bit as i was curious about this file and looking at the `EGP_01_NR.js ` history it seems to be related with analytics, it was added at the same time as Google Analytics. we used google analytics everywhere and i have checked other NV divisions (fungi, metazoa) and they only have the _GA.js file. It seems to be only for plants and i think it is safe to remove it. 

And yes by removing the js file the DHTMLmerge.pm wont pick it up. But there is also one more thing that i noticed that it is a .min.js so it is also something that gets generated on server restart when there is no minified javascript. Keep an eye on the minified javascripts as well once this fix is pushed.

**Review by ens-ap5 — COMMENTED** [review]
I'll defer to Ridwan on this one - his comments seem to cover everything

**Review by jyothishnt — APPROVED** [review]

**Pull request merged**
