### PR TITLE
Update zea_mays.ini

### PR DESCRIPTION
**Pull request by weix-cshl**
Remove the tracks whose data was mapped on AGPv4, may restore them once the data is remapped to AGPv5

### CODE REVIEW

**Comment by gnaamati** [comment]
PR from Gramene after discussion with me, removing incorrect tracks from Maize

**Comment by gnaamati** [comment]
@ens-ds23 is there any update on this?

**Comment by ens-ap5** [comment]
@gnaamati This needs to be submitted against the postreleasefix/eg/51 branch, otherwise it won't go into release 105.

**Comment by ens-ap5** [comment]
This can be closed - replaced by #45

**Pull request closed without merging**
